services:

  tls-cert-generator:
    container_name: tls-cert-generator-cnt
    build: .
    volumes:
      - ./certs:/app/certs
    environment:
      # TLS Certificate settings...
      COUNTRY: "XX"
      STATE: "XXX"
      LOCALITY: "XXX"
      ORGANIZATION: "XXX"
      ORGANIZATIONAL_UNIT: "XXX"
      ROOT_CN: "tls-cert-generator@XXX"
    network_mode: "host"   # use the host network to get public IPs/hostnames
    command: [ "all", "1.2.3.4", "example.com" ]  # use comma-seperated commands/IPs/hostnames/FQDNs to create TLS certificates
