name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag (e.g. v1.0.0)"
        required: true
        default: "latest"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/certificate-manager:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/certificate-manager:${{ github.event.inputs.image_tag }}
